title: Minimal theme
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

title: hola ASIR2

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
    # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

collections:
  members:
    output: true



# número de posts por página
paginate: 2
paginate_path: /blog/page:num/



minima:
  skin: dark

name: alvaro lopez
  
